# config/cucumber.yml
##YAML Template

android: PLATFORM=android --exclude features/ios

ios: PLATFORM=ios --exclude features/android

bruno: QA=bruno

jenkins: QA=jenkins -f json -o reports/report.json

jenkinsReal: QA=jenkins_realDevice -f json -o reports/report.json

jenkinsReal1: QA=jenkins_realDevice_1 -f json -o reports/report.json