# config/cucumber.yml
##YAML Template

android: PLATFORM=android --exclude features/ios

ios: PLATFORM=ios --exclude features/android

bruno: QA=bruno

jenkins: QA=jenkins -f json -0 reports/report.json